### PR TITLE
add platformio library manifest

### PR DESCRIPTION
**Pull request by glynhudson**
http://platformio.org/lib/

### CODE REVIEW

**Comment by marvinroger** [comment]
Can you remove `atmelsam`? It's not compatible with ATMEL as it uses some ESP8266-specific stuff.

**Comment by glynhudson** [comment]
Wops, it's been removed

**Comment by rudacs** [comment]
Could you please do the merge. To be able to add in the platformio.
Thank you.

**Comment by marvinroger** [comment]
My bad, thanks @glynhudson

**Pull request merged**
